# Disable if urgent issue! (Use /ah toggle)
enabled: true

listing-price:
  min: 1
  max: 1000000000

default-max-listings: 3
decimal-format: "#,###.00"

listing-adverts:
  # If default is true, when creating a new listing, if they do not want to purchase an advert they must click the toggle button
  # If default is false, when creating a new listing, if they want to purchase an advert they must click the toggle button
  default: false
  # How much it costs to advertise the listing by default (can be 0 for free)
  # Overridden by the fadah.advert-price.<amount> permission
  price: 100.0

hooks:
  bedrock: false
  eco-items: false
  discord:
    enabled: false
    webhook-url: "INSERT WEBHOOK URL HERE"
    # If this is true the webhook will only send a message when the listing has been advertised (config above)
    only-send-on-advert: false
    # Supported: EMBED, PLAIN
    mode: "EMBED"
    # If mode is EMBED
    embed:
      # Supported: SIDE, BOTTOM
      image-location: SIDE
      title: "New Listing by %player%!"
      content: "%player% just listed %item% for $%price% on the auction house!"
      footer: "Powered by Finally a Decent Auction House"
    # If mode is PLAIN
    plain-text: "%player% just listed %item% for $%price% on the auction house!"

migrators:
  z-auction-house:
    categories-to-migrate:
      - "Blocks"
      - "Tools"
      - "Weapons"
      - "Potions"
      - "Misc"

  auction-house:
    no-settings: "This Migrator has no settings!"

log-to-file: true

database:
  # Supported: SQLITE, MYSQL, MARIADB, MONGO
  type: "SQLITE"
  # Below is not required for SQLITE
  # For MySQL and MariaDB, uri must be a JDBC uri
  uri: "jdbc:mysql://username:password@127.0.0.1:3306/Fadah"
  database: "Fadah"

# A message broker is only required for x-server environments.
# This mode is not compatible with SQLITE database
broker:
  enabled: false
  type: "REDIS"
  # Snapchat's KeyDB is recommended as it is 2x faster than normal redis while still fully compatible.
  redis:
    host: "127.0.0.1"
    port: 6379
    password: "password"
    channel: "auctionhouse.cache"

# Enable this if you are experiencing dupes (usually when there is a moderate delay with redis)
strict-checks: false